spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/serverdb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
    show-sql: true
